version: '3.1'
services:
  backend:
    image: 'gcr.io/balmy-script-278222/thegame:1.07'
    env_file:
      - 'thegame.env'
    ports:
      - '9000:9000'
  frontend:
    depends_on:
      - 'backend'
    image: 'gcr.io/balmy-script-278222/thegame-nginx:1.07'
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
